# Generated by Django 6.0.6 on 2026-07-31 18:37

import django.db.models.deletion
from django.db import migrations, models


def copy_direction_from_service(apps, schema_editor):
    Magasin = apps.get_model("stock", "Magasin")
    for magasin in Magasin.objects.select_related("id_service", "id_service__id_direction").all():
        if magasin.id_direction_id or not magasin.id_service_id:
            continue
        magasin.id_direction_id = magasin.id_service.id_direction_id
        magasin.save(update_fields=["id_direction"])


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_scoped_organisation_codes'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magasin',
            name='id_direction',
            field=models.ForeignKey(blank=True, db_column='id_direction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magasins', to='organisation.direction'),
        ),
        migrations.RunPython(copy_direction_from_service, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='materiel',
            name='etat',
            field=models.CharField(choices=[('NEUF', 'Neuf'), ('BON', 'Bon état'), ('EN_STOCK', 'En stock'), ('AFFECTE', 'Affecté'), ('EN_PANNE', 'En panne'), ('EN_REPARATION', 'En réparation'), ('HORS_SERVICE', 'Hors service')], default='NEUF', max_length=20),
        ),
    ]
