# Generated by Django 6.0.6 on 2026-08-05 20:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_separate_materiel_state_and_stock_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='date_achat',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
