# Generated by Django 6.0.6 on 2026-08-06 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0006_remove_users_id_magasin_alter_users_scope_type'),
        ('operations', '0007_remove_mouvementstock_magasin_destination_and_more'),
        ('stock', '0004_alter_materiel_date_achat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiel',
            name='id_magasin',
        ),
        migrations.RemoveField(
            model_name='consommable',
            name='id_magasin',
        ),
        migrations.DeleteModel(
            name='Magasin',
        ),
    ]
