# Generated by Django 6.0.6 on 2026-07-20 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventaires", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inventaire",
            name="cree_par",
            field=models.ForeignKey(
                blank=True,
                db_column="cree_par",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventaires_crees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inventaire",
            name="effectue_par_libre",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
