# Generated by Django 6.0.6 on 2026-07-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaires', '0002_inventaire_cree_par_inventaire_effectue_par_libre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventaire',
            name='entite_type',
            field=models.CharField(choices=[('DEPARTEMENT', 'Département'), ('DIRECTION', 'Direction'), ('MAGASIN', 'Magasin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='statut',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='EN_COURS', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='type_inventaire',
            field=models.CharField(choices=[('GENERAL', 'Général'), ('PARTIEL', 'Partiel'), ('PERIODIQUE', 'Périodique'), ('EXCEPTIONNEL', 'Exceptionnel')], default='GENERAL', max_length=20),
        ),
    ]
