# Generated by Django 6.0.6 on 2026-08-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaires', '0003_alter_inventaire_entite_type_alter_inventaire_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventaire',
            name='entite_type',
            field=models.CharField(choices=[('DEPARTEMENT', 'Département'), ('DIRECTION', 'Direction')], max_length=20),
        ),
    ]
