# Generated by Django 6.0.6 on 2026-07-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_convert_users_to_django_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='scope_type',
            field=models.CharField(choices=[('GENERAL', 'Général'), ('DEPARTEMENT', 'Département'), ('DIRECTION', 'Direction'), ('SERVICE', 'Service'), ('MAGASIN', 'Magasin')], default='GENERAL', max_length=20),
        ),
    ]
