# Generated by Django 6.0.6 on 2026-07-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_alter_users_scope_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='scope_type',
            field=models.CharField(choices=[('GENERAL', 'Général'), ('DEPARTEMENT', 'Département'), ('DIRECTION', 'Direction'), ('MAGASIN', 'Magasin')], default='GENERAL', max_length=20),
        ),
    ]
