# Generated by Django 6.0.6 on 2026-08-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0005_alter_users_scope_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id_magasin',
        ),
        migrations.AlterField(
            model_name='users',
            name='scope_type',
            field=models.CharField(choices=[('GENERAL', 'Général'), ('DEPARTEMENT', 'Département'), ('DIRECTION', 'Direction')], default='GENERAL', max_length=20),
        ),
    ]
