# Generated by Django 6.0.6 on 2026-07-31 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_affectation_traceability'),
        ('organisation', '0002_scoped_organisation_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation',
            name='agent_id_departement',
            field=models.ForeignKey(blank=True, db_column='agent_id_departement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_agents', to='organisation.departement'),
        ),
        migrations.AddField(
            model_name='affectation',
            name='agent_id_direction',
            field=models.ForeignKey(blank=True, db_column='agent_id_direction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_agents', to='organisation.direction'),
        ),
        migrations.AddField(
            model_name='affectation',
            name='agent_id_service',
            field=models.ForeignKey(blank=True, db_column='agent_id_service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_agents', to='organisation.service'),
        ),
        migrations.AddField(
            model_name='affectation',
            name='agent_matricule',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='affectation',
            name='agent_nom_complet',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='affectation',
            name='agent_telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='entite_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='entite_type',
            field=models.CharField(choices=[('DEPARTEMENT', 'DÃ©partement'), ('DIRECTION', 'Direction'), ('SERVICE', 'Service'), ('UTILISATEUR', 'Utilisateur'), ('AGENT', 'Agent'), ('MAGASIN', 'Magasin')], max_length=20),
        ),
    ]
