# Generated by Django 6.0.6 on 2026-07-31 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_affectation_agent_id_departement_and_more'),
        ('organisation', '0002_scoped_organisation_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='consommation',
            name='destination_type',
            field=models.CharField(choices=[('DEPARTEMENT', 'Departement'), ('DIRECTION', 'Direction'), ('SERVICE', 'Service')], default='DEPARTEMENT', max_length=20),
        ),
        migrations.AddField(
            model_name='consommation',
            name='id_departement',
            field=models.ForeignKey(blank=True, db_column='id_departement', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consommations', to='organisation.departement'),
        ),
        migrations.AddField(
            model_name='consommation',
            name='id_direction',
            field=models.ForeignKey(blank=True, db_column='id_direction', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consommations', to='organisation.direction'),
        ),
        migrations.AddField(
            model_name='consommation',
            name='id_service',
            field=models.ForeignKey(blank=True, db_column='id_service', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consommations', to='organisation.service'),
        ),
    ]
