# Generated by Django 6.0.6 on 2026-07-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_consommation_destination_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='entite_type',
            field=models.CharField(choices=[('DEPARTEMENT', 'DÃ©partement'), ('DIRECTION', 'Direction'), ('UTILISATEUR', 'Utilisateur'), ('AGENT', 'Agent'), ('MAGASIN', 'Magasin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='consommation',
            name='destination_type',
            field=models.CharField(choices=[('DEPARTEMENT', 'Departement'), ('DIRECTION', 'Direction')], default='DEPARTEMENT', max_length=20),
        ),
    ]
