# Generated by Django 6.0.6 on 2026-08-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0005_alter_affectation_entite_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affectation",
            name="entite_type",
            field=models.CharField(
                choices=[
                    ("DEPARTEMENT", "Departement"),
                    ("DIRECTION", "Direction"),
                    ("AGENT", "Agent"),
                    ("MAGASIN", "Magasin"),
                ],
                max_length=20,
            ),
        ),
    ]
