# Generated by Django 6.0.6 on 2026-08-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_alter_affectation_entite_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouvementstock',
            name='magasin_destination',
        ),
        migrations.RemoveField(
            model_name='mouvementstock',
            name='magasin_source',
        ),
        migrations.AlterField(
            model_name='affectation',
            name='entite_type',
            field=models.CharField(choices=[('DEPARTEMENT', 'Departement'), ('DIRECTION', 'Direction'), ('AGENT', 'Agent')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='type_mouvement',
            field=models.CharField(choices=[('ENTREE', 'EntrÃ©e'), ('SORTIE', 'Sortie'), ('AJUSTEMENT', 'Ajustement')], max_length=20),
        ),
    ]
