# Generated by Django 6.0.6 on 2026-06-25 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id_departement', models.AutoField(primary_key=True, serialize=False)),
                ('code_departement', models.CharField(max_length=20, unique=True)),
                ('nom_departement', models.CharField(max_length=100)),
                ('abreviation', models.CharField(blank=True, max_length=10, null=True)),
                ('statut', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'departement',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id_direction', models.AutoField(primary_key=True, serialize=False)),
                ('code_direction', models.CharField(max_length=20, unique=True)),
                ('nom_direction', models.CharField(max_length=100)),
                ('abreviation', models.CharField(blank=True, max_length=10, null=True)),
                ('statut', models.BooleanField(default=True)),
                ('id_departement', models.ForeignKey(db_column='id_departement', on_delete=django.db.models.deletion.PROTECT, related_name='directions', to='organisation.departement')),
            ],
            options={
                'db_table': 'direction',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.AutoField(primary_key=True, serialize=False)),
                ('code_service', models.CharField(max_length=20, unique=True)),
                ('nom_service', models.CharField(max_length=100)),
                ('abreviation', models.CharField(blank=True, max_length=10, null=True)),
                ('statut', models.BooleanField(default=True)),
                ('id_direction', models.ForeignKey(db_column='id_direction', on_delete=django.db.models.deletion.PROTECT, related_name='services', to='organisation.direction')),
            ],
            options={
                'db_table': 'service',
            },
        ),
    ]
