# Generated by Django 6.0.6 on 2026-06-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id_departement', models.FloatField(primary_key=True, serialize=False)),
                ('code_departement', models.CharField(max_length=20, unique=True)),
                ('nom_departement', models.CharField(max_length=100)),
                ('abreviation', models.CharField(max_length=10)),
                ('statut', models.BooleanField()),
            ],
            options={
                'db_table': 'DEPARTEMENT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id_direction', models.FloatField(primary_key=True, serialize=False)),
                ('code_direction', models.CharField(max_length=20, unique=True)),
                ('nom_direction', models.CharField(max_length=100)),
                ('abreviation', models.CharField(max_length=10)),
                ('statut', models.BooleanField()),
            ],
            options={
                'db_table': 'DIRECTION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.FloatField(primary_key=True, serialize=False)),
                ('code_service', models.CharField(max_length=20, unique=True)),
                ('nom_service', models.CharField(max_length=100)),
                ('abreviation', models.CharField(max_length=10)),
                ('statut', models.BooleanField()),
            ],
            options={
                'db_table': 'SERVICE',
                'managed': False,
            },
        ),
    ]
