# Generated by Django 6.0.6 on 2026-06-25 20:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id_magasin', models.AutoField(primary_key=True, serialize=False)),
                ('code_magasin', models.CharField(max_length=20, unique=True)),
                ('nom_magasin', models.CharField(max_length=100)),
                ('description_localisation', models.CharField(blank=True, max_length=500, null=True)),
                ('date_creation', models.DateField(default=django.utils.timezone.localdate)),
                ('statut', models.BooleanField(default=True)),
                ('id_service', models.ForeignKey(blank=True, db_column='id_service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magasins', to='organisation.service')),
            ],
            options={
                'db_table': 'magasin',
            },
        ),
        migrations.CreateModel(
            name='Consommable',
            fields=[
                ('id_consommable', models.AutoField(primary_key=True, serialize=False)),
                ('code_consommable', models.CharField(max_length=25, unique=True)),
                ('nom_consommable', models.CharField(max_length=100)),
                ('quantite_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('seuil_alerte', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_creation', models.DateField(default=django.utils.timezone.localdate)),
                ('statut', models.BooleanField(default=True)),
                ('id_categorie', models.ForeignKey(db_column='id_categorie', on_delete=django.db.models.deletion.PROTECT, related_name='consommables', to='catalogue.categorie')),
                ('id_unite', models.ForeignKey(db_column='id_unite', on_delete=django.db.models.deletion.PROTECT, related_name='consommables', to='catalogue.unitemesure')),
                ('id_magasin', models.ForeignKey(blank=True, db_column='id_magasin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consommables', to='stock.magasin')),
            ],
            options={
                'db_table': 'consommable',
            },
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id_materiel', models.AutoField(primary_key=True, serialize=False)),
                ('code_materiel', models.CharField(max_length=25, unique=True)),
                ('numero_serie', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(blank=True, max_length=150, null=True)),
                ('date_achat', models.DateField()),
                ('date_mise_en_service', models.DateField(blank=True, null=True)),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=13)),
                ('devise', models.CharField(default='USD', max_length=10)),
                ('duree_garantie_mois', models.PositiveIntegerField(default=0)),
                ('garantie_fin', models.DateField(blank=True, null=True)),
                ('etat', models.CharField(choices=[('NEUF', 'Neuf'), ('BON', 'Bon état'), ('EN_STOCK', 'En stock'), ('AFFECTE', 'Affecté'), ('EN_PANNE', 'En panne'), ('EN_REPARATION', 'En réparation'), ('HORS_SERVICE', 'Hors service')], default='NEUF', max_length=20)),
                ('code_barre', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('qr_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('date_enregistrement', models.DateField(default=django.utils.timezone.localdate)),
                ('observation', models.CharField(blank=True, max_length=500, null=True)),
                ('id_categorie', models.ForeignKey(db_column='id_categorie', on_delete=django.db.models.deletion.PROTECT, related_name='materiels', to='catalogue.categorie')),
                ('id_fournisseur', models.ForeignKey(blank=True, db_column='id_fournisseur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiels', to='catalogue.fournisseur')),
                ('id_magasin', models.ForeignKey(blank=True, db_column='id_magasin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiels', to='stock.magasin')),
            ],
            options={
                'db_table': 'materiel',
            },
        ),
    ]
