# Generated by Django 6.0.6 on 2026-07-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_remove_entretien_planifie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretien',
            name='statut',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='EN_COURS', max_length=20),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='type_entretien',
            field=models.CharField(choices=[('PREVENTIF', 'Préventif'), ('CORRECTIF', 'Correctif'), ('CONTROLE', 'Contrôle')], default='PREVENTIF', max_length=20),
        ),
        migrations.AlterField(
            model_name='reparation',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20),
        ),
    ]
