# Generated by Django 6.0.6 on 2026-07-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0003_demande_id_consommable_demande_id_materiel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='origine_type',
            field=models.CharField(choices=[('DEPARTEMENT', 'Departement'), ('DIRECTION', 'Direction'), ('MAGASIN', 'Magasin')], default='DIRECTION', max_length=20),
        ),
    ]
