# Generated by Django 6.0.6 on 2026-08-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0004_alter_demande_origine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='origine_type',
            field=models.CharField(choices=[('DEPARTEMENT', 'Departement'), ('DIRECTION', 'Direction')], default='DIRECTION', max_length=20),
        ),
    ]
